# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rzKhrQHgEwXNvlH16ZVYh94oXh4EECwX
"""

name="Amaar Raza"
occupation = "Software Engineering"

print(" I am {} and I am an Expert {}".format(name, occupation))

"""#task2"""

name="Amaar Raza"
occupation = "Software Engineering"



print(name.capitalize())
print(occupation.islower())
print(name.upper())
print(name.swapcase())
print(name.replace('Amaar', 'Ali'))

"""#task 3"""

month = 8
days_in_month = [31,28,31,30,31,30,31,31,30,31,30,31]

num_of_day=days_in_month[month-1]

print(num_of_day)

"""#task 4"""

dates = ['June 21, 2001', 'December 4, 2002', 'November 23, 2003','March 29, 2006', 'August 1, 2008', 'July 22, 2009','July 11, 2010', 'November 13, 2012', 'March 20, 2015','March 9, 2016']
mostDates = dates[-3:]
print(mostDates)

"""# Task 5

"""

student = {"20sw014": {'name': 'Mahmood', 'age': '18', 'gender': 'Male',"Department":"Software","Section":"i","University":"MUET jamshoro"},
          "20sw067": {'name': 'Shahzad', 'age': '22', 'gender': 'Male',"Department":"Software","Section":"i","University":"MUET jamshoro"},
          "20sw002": {'name': 'Rameez', 'age': '22', 'gender': 'Male',"Department":"Software","Section":"i","University":"MUET jamshoro"},
          "20sw015": {'name': 'Kashif', 'age': '20', 'gender': 'Female',"Department":"Software","Section":"i","University":"MUET jamshoro"},
          "20sw040": {'name': 'Ali Haider', 'age': '18', 'gender': 'Male',"Department":"Software","Section":"i","University":"MUET jamshoro"},
          "20sw023": {'name': 'Ashir', 'age': '22', 'gender': 'Male',"Department":"Software","Section":"i","University":"MUET jamshoro"}}

print(student)